### ISSUE TITLE
Bug at simple printing code

### ISSUE THREAD

**Issue by mehanalavimajd** [sacalon/sacalon#10]
**Hascal version: newest I think 1.3.5 or 1.3.6**

**OS: Ubuntu 20.04**

**What did you do?**
```
function main() :int{
        print("hello world")
        return 0
}
```
**What did you expect to see?**
Hello world
**What did you see instead?**
`Error : Illegal character '"':2`

**Comment by bistcuite** [comment]
Bug fixed in [this commit](https://github.com/hascal/hascal/commit/764365857a0277c3f3c941c51d1acbe0d4c61594), reclone your hascal repo.

**Comment by mehanalavimajd** [comment]
I will reinstall it today
