### ISSUE TITLE
Documentation and Roadmap links in README.md appears to be broken 

### ISSUE THREAD

**Issue by ziord** [sacalon/sacalon#32]
**Hascal version:**
N/A
**OS:**
N/A
**What did you do?**
Tried checking out the docs and project roadmap on the readme page (at the bottom of the file) but both links appear to be broken.   
**What did you expect to see?**
Both pages 
**What did you see instead?**
404 / Not Found

**Comment by bistcuite** [comment]
Thank you for reporting 🌷

Links changed in the readme.

[Docs](https://hascal.github.io/docs/latest)

[Roadmap](https://github.com/hascal/hascal/blob/main/docs/ROADMAP.md)
