### ISSUE TITLE
What if you host Hascal's docs on readthedocs.io

### ISSUE THREAD

**Issue by lnxpy** [sacalon/sacalon#4]
First of all, THIS LANGUAGE IS :fire:!
I truly like its concepts and basics. Congrats. 🌹

By the way, I was trying to check the docs and noticed that you are using Github MarkDown in order to store and keep those docs. I highly recommend you to use [SphinX](https://www.sphinx-doc.org/en/master/) in order to generate Hascal's docs and consider hosting the documentations on a webserver like [readthedocs.io](https://readthedocs.io) or [github.io](https://github.io).

> Please consider adding the `enhancement` label.

Thanks.

**Comment by bistcuite** [comment]
We are currently trying to make Hascal more stable and then the documentation will be available on [https://github.io](https://github.io).
`enhancement` label now exists.

**Comment by bistcuite** [comment]
The Hascal documentation now available [here](https://hascal.github.io/docs/index.html). It created with [mkdocs](https://mkdocs.org).

**Comment by lnxpy** [comment]
Cool. :heart:
