### ISSUE TITLE
Not erroring when there is no return values in main()

### ISSUE THREAD

**Issue by mehanalavimajd** [sacalon/sacalon#66]
**Is your feature request related to a problem? Please describe.**
This following code:
```typescript
function main():int{
    print("Hello world")
}
```
Would return the error:
```
Error : Function 'main' should return a value at end of function block:1
```
So In other languages like c++ There is no need to put `return 0;` in latest versions. 
Basically, We must ignore not returning if function name is `main`

**Comment by bistcuite** [comment]
Merged!
